FRAME_RATE = 60

SCREEN_WIDTH = 500
SCREEN_HEIGHT = 620

GRID_WIDTH_HEIGHT = 300
GRID_SIZE_XY = 4

GRID_OFFSET_X = 11
GRID_OFFSET_Y = 11

CELL_SIZE = GRID_WIDTH_HEIGHT / GRID_SIZE_XY

# NEXT_BLOCK_OFFSET_X = 340
# NEXT_BLOCK_OFFSET_Y = 260